config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:create, :index, :show, :edit, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, length: {minimum: 2, maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      user_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @user = @book_show.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
    render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @book = Book.new
    @user_index = User.all
  end



  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end



 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
      <div class="error-message">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% end %>
      </div>
        <div class="row">
          <div class="col-md-3">
            <h2>User info</h2>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
              <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do%>
              <i class= "fas fa-user-cog"></i>
              <% end %>
            </div>
            <h2 class="mt-3">New book</h2>
            <!--form_with部分-->
            <%= form_with model:book, local:true do |f| %>
              <div class="form-group">
                <label for="book_title">title</label>
                　<%= f.text_field :title %>
              </div>
              <div class="form-group">
                <label for="book_opinion">Opinion</label>
                　<%= f.text_area :body %>
              </div>
              <div class="form-group">
                <%= f.submit "Create Book", class: "btn btn-success btn-sm btn-block mb-3" %>
         </div>
       </div>
              <% end %>

app/views/books/edit.html.erb
      <p id="notice"></p>
      <div class="containar">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h1>Editing Book</h1>
             <div class="error-message">
               <% if @book.errors.any? %>
                 <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
                     <% @book.errors.full_messages.each do |message| %>
                       <ul>
                         <li><%= message %></li>
                       </ul>
                     <% end %>
               <% end %>
             </div>
            <%= form_with model:@book, local:true do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
               　<div><%= f.text_field :title %></div>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
               　<div><%= f.text_area :body %></d
            </div>
            <div class="form-group">
              <%= f.submit "Update Book", class: "btn btn-success" %>
            </div>
           <% end %>
           <%= link_to "Show", book_path(@book.id) %>
           |
           <%= link_to "Back", books_path %>
          </div>
        </div>
      </div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/book', user: @user, book: @book %>
              <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Title</th>
                      <th>Opinion</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @books.each do |book| %>
                      <tr>
                        <td>
                          <%= link_to user_path(book.user.id) do %>
                            <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
                          <% end %>
                        </td>
                        <td><%= link_to book.title, book_path(book.id) %></td>
                        <td><%= book.body %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
  </div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'users/user' %>
    <%= render "books/book", user: @user, book: @book %>
      <div class="col-md-8 offset-md-1">
                <h2>Book detail</h2>
                <table class="table">
                  <tbody>
                      <tr>
                        <td>
                          <%= link_to user_path(@user.id) do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                              <div><%= @user.name %></div>
                          <% end %>
                        </td>
                        <td><%= link_to @book_show.title, book_path(@book_show.id) %></td>
                        <td><%= @book_show.body %></td>
                        <% if @book_show.user == current_user %>
                        <td><%= link_to "Edit", edit_book_path(@book_show.id), class: "btn btn-sm btn-success" %></td>
                        <td><%= link_to "Destroy", book_path(@book_show), method: :delete, data: {confirm: '本当に削除しますか？'},  class: "btn btn-sm btn-danger" %></td>
                        <% end %>
                      </tr>
                  </tbody>
                </table>
      </div>
 </div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
      <main>
        <p id="notice"></p>
        <div class="containar">
          <div class=row>
            <h1 class="px-3 mx-auto">
              Welcom to
            <i class="fas fa-book"></i>
            <strong>
              Bookers
            </strong>
            !
            </h1>
        </div>
      </main>
    </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"> <!-- 追加 -->

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <main>
      <%= render "users/user" %>
      <div class="containar">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
              welcom to
              <i class="fas fa-book"></i>
              <strong>Bookers</strong>
               !!
            </h1>
            <p>
              In
              <i class="fas fa-book"></i>
              <strong>Bookers</strong>
              ,
            </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <%= link_to "Log in", new_user_session_path , class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
              </div>
              <div class="row">
                <%= link_to "Sign up",new_user_registration_path, class: "btn btn-success btn-sm btn-block Sign_up" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--FontAwesome-->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
      <header class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <nav class = "nav navbar-brand">
              <%= link_to "Bookers", root_path, class: "text-white" %>
            </nav>
            <ul class = "nav navbar-navbar-right">
                <% if user_signed_in? %>
                    <li class="navbar-text">
                      <%= link_to "Home", user_path(current_user.id), class: "fas fa-home" %>
                    </li>
                    <li class="navbar-text">
                      <%= link_to "Users", users_path, class: "fas fa-users ml-3" %>
                    </li>
                    <li class="navbar-text">
                      <%= link_to "Books", books_path, class: "fas fa-book-open ml-3" %>
                    </li>
                    <li class="navbar-text">
                      <%=link_to "Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt ml-3" %>
                    </li>
                <% else %>
                    <li class="navbar-text">
                       <%= link_to "Home", root_path, class: "fas fa-home" %>
                    </li>
                    <li class="navbar-text">
                       <%= link_to "About", home_about_path, class: "fas fa-link" %>
                    </li>
                    <li class="navbar-text">
                       <%= link_to "Sign up", new_user_registration_path, class: "fas fa-user-plus" %>
                    </li>
                    <li class="navbar-text">
                       <%= link_to "Log in", new_user_session_path, class: "fas fa-sign-in-alt" %>
                    </li>
                 <% end %>
            </ul>
        </div>
      </header>
      <main>
      </main>
      <%= yield %>
      <footer>
        <div class="containar mt-5">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
  </body>
</html>

app/views/users/_user.html.erb
<div>
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>

app/views/users/edit.html.erb
      <p id="notice"></p>
        <div class="containar">
          <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
              <h2>User info</h2>
              <div class="error-message">
               <% if @user.errors.any? %>
                 <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
                     <% @user.errors.full_messages.each do |message| %>
                       <ul>
                         <li><%= message %></li>
                       </ul>
                     <% end %>
               <% end %>
             </div>
                <%= form_with model:@user, local:true do |f| %>
                <div class="form-group mt-3">
                  <label for="user_name">Name</label>
                    <div class="form-controll name"><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></div>
                </div>
                <div class="form-group">
                  <label for="user_image">Image</label>
                    <div class="form-controll-file user_image"> <%= f.attachment_field :profile_image %></div>
                </div>
                <div class="form-group">
                  <label for="user_introduction">Introduction</label>
                  <div class="form-controll introduction"><%= f.text_area :introduction %></div>
                </div>
                    <%= f.submit "Update User", class: "btn btn-secondary" %>
                <% end %>
            </div>
          </div>
        </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/book', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
                <h2>Users</h2>
                <table class="table table-hover table-inverse">
                  <thead>
                    <tr>
                      <th>image</th>
                      <th>name</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @user_index.each do |user| %>
                      <tr>
                        <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %></td>
                        <td><%= user.name %></td>
                        <td><%= link_to "Show", user_path(user.id) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>

    </div>
 </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'users/user' %>
    <%= render 'books/book', user: @user, book: @book %>
      <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Title</th>
                      <th>Opinion</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @books.each do |book| %>
                      <tr>
                        <td>
                          <%= link_to user_path(book.user.id) do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
                          <% end %>
                        </td>
                        <td><%= link_to book.title, book_path(book.id) %></td>
                        <td><%= book.body %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
      </div>
</div>